export const apiUrls = {
  baseUrl: 'https://new-stellarburgers.education-services.ru/api/',
  getIngredients: 'ingredients',
  createOrder: 'orders',
  getOrder: 'orders',
  register: 'auth/register',
  login: 'auth/login',
  logout: 'auth/logout',
  refreshToken: 'auth/token',
  getUser: 'auth/user',
  updateUser: 'auth/user',
  forgotPassword: 'password-reset',
  resetPassword: 'password-reset/reset',
  wsAllOrders: 'wss://new-stellarburgers.education-services.ru/orders/all',
  wsUserOrders: 'wss://new-stellarburgers.education-services.ru/orders',
};
